"""Change efficiency to Float for automatic calculation

Revision ID: 2fe2f60cbb71
Revises: 
Create Date: 2025-07-02 09:56:22.146149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe2f60cbb71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_data', schema=None) as batch_op:
        batch_op.alter_column('efficiency',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('weekly_data', schema=None) as batch_op:
        batch_op.alter_column('efficiency',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_data', schema=None) as batch_op:
        batch_op.alter_column('efficiency',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('daily_data', schema=None) as batch_op:
        batch_op.alter_column('efficiency',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
