"""Add created_at to CountdownEvent

Revision ID: d99b0806b340
Revises: 
Create Date: 2025-07-03 11:23:58.798919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99b0806b340'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countdown_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countdown_event', schema=None) as batch_op:
        batch_op.drop_column('created_at_utc')

    # ### end Alembic commands ###
