# .github/workflows/deploy.yml
name: Deploy to Aliyun ECS

# 触发条件：当代码被推送到 main 分支时
on:
  push:
    branches:
      - main # 如果你的主分支是 master，请把这里改成 master

# 任务
jobs:
  deploy:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 步骤一：检出（下载）你的代码到虚拟环境
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤二：连接到你的阿里云服务器并执行部署命令
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/my-learning-logger
            git pull
            echo "Running update script..."
            sh ./.update.sh
            echo "Deployment successful!"