# .github/workflows/deploy.yml
name: Deploy to Aliyun ECS

# 触发条件：当代码被推送到 main 分支时
on:
  push:
    branches:
      - main # 如果你的主分支是 master，请把这里改成 master

# 任务
jobs:
  deploy:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 步骤一：检出（下载）你的代码到虚拟环境
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤二：连接到你的阿里云服务器并执行部署命令
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "--- 1. 开始调试 ---"
            echo "登录用户: $(whoami)"
            echo "当前路径: $(pwd)"
            
            echo "--- 2. 进入项目目录 ---"
            cd /root/my-learning-logger
            echo "进入后路径: $(pwd)"
            
            echo "--- 3. 检查Git远程地址 ---"
            git remote -v
            
            echo "--- 4. 尝试拉取代码 ---"
            git pull
            echo "--- Git Pull 命令执行完毕 ---"
            
            echo "--- 5. 再次检查最新commit ---"
            git log -1
            
            echo "--- 6. 执行更新脚本 ---"
            sh ./.update.sh
            echo "--- 部署脚本执行完毕 ---"